---
  - name: Update and upgrade apt packages
    become: true
    apt:
        upgrade: yes
        update_cache: yes

  - name: Install Apache, PHP and MariaDB
    apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
    with_items: "{{ packages }}"

  - name: Starting Apache
    systemd:
        state: started
        name: apache2
        enabled: yes

  - name: Starting Mysql
    systemd:
        state: started
        name: mysql
        enabled: yes

  - name: Installing Zabbix Server
    become: true
    get_url:
        url: http://repo.zabbix.com/zabbix/3.0/debian/pool/main/z/zabbix-release/zabbix-release_3.0-2+stretch_all.deb
        dest: /home/geroy/Downloads
		
  - name: Installing Zabbix Server
    apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
    with_items: "{{ zabbix }}"

  - name: dpkg zabbix
    dpkg_selections:
        name: zabbix-release_3.0-2+stretch_all.deb
        selection: install

  - name: Starting zabbix
    systemd:
        state: started
        name: zabbix-agent
        enabled: yes
		
  - name: Create a new database with name 'zabbixdb'
    mysql_db:
        name: zabbixdb
        collation: utf8_general_ci
        encoding: utf8
        state: present

  - name: Create user
    mysql_user:
        name: geroy
        host: localhost
        password: 12345
        priv: '*.*:ALL'
        state: present

  - name: Edit file 'zabbix_server.conf'
    blockinfile:
        path: '{{ zbconf }}'
        block: |
          {{ zbdbname }}
          {{ zbdbuser }}
          {{ zbdbpassword }}
          {{ zbdbhost }}

  - name: Touch /etc/zabbix/apache.conf
    file:
        path: /etc/zabbix/apache.conf
        state: touch

  - name: Edit file 'apache.conf'
    blockinfile:
        path: '{{ apconf }}'
        block: |
          php_value max_execution_time 300
          php_value memory_limit 128M
          php_value post_max_size 32M
          php_value upload_max_filesize 8M
          php_value max_input_time 300
          php_value always_populate_raw_post_data -1
          php_value date.timezone Asia/Kolkata

  - name: Restarting services
    systemd:
       state: restarted
       name: '{{ item }}'
    with_items: '{{ services }}'

  - name: Copy apacheconf to zabbixconf
    copy:
      src: '{{ appath }}'
      dest: '{{ zbpath }}'